[providers.google]
issuer_url = "https://accounts.google.com"
client_id = "ABCDE"
client_secret = "12345"

[providers.keycloak]
issuer_url = "http://localhost:8080/realms/mbs4"
client_id = "mbs4"
client_secret = "xxxxxx"

[providers.keycloak2]
issuer_url = "http://localhost:8080/realms/test"
client_id = "mbs4"
client_secret = "xxxxxx"
