[package]
name = "mbs4-image"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
image = { version = "0.25.9" }
anyhow = { workspace = true }
fast_image_resize = { version = "5.5.0", features = ["image"] }
